version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - IMAGE_TAG=v1.$CODEBUILD_BUILD_NUMBER
      - REPO_URI=382828593676.dkr.ecr.us-east-1.amazonaws.com/spring-demo-ecr
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPO_URI

  build:
    commands:
      - echo Building the JAR file...
      - mvn clean install -DskipTests
      - echo Building Docker image...
      - docker build -t spring-demo-ecr:$IMAGE_TAG .
      - docker tag spring-demo-ecr:$IMAGE_TAG $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Creating deployment manifests...
      - sed "s|IMAGE_PLACEHOLDER|$REPO_URI:$IMAGE_TAG|g" k8s/deployment.yaml > deployment.yaml
      - cp k8s/service.yaml service.yaml
      - echo "✅ Files in root directory:"
      - ls -la
      - echo "🔍 deployment.yaml content:"
      - cat deployment.yaml

artifacts:
  base-directory: .
  files:
    - deployment.yaml
    - service.yaml
  discard-paths: no
